"""Pose refits: the post-ODE (translation, scale) refit and the ICP pose refine.

**(t, s) refit.**  Before the Stage-1 rotation exists, a depth-grounded placement can
only read the observation (mask bbox, median masked depth, K), so it is rotation-BLIND
and its two errors are functions of the rotation it does not know:

* **foreshortening** — it reads a 2D PROJECTED span but the canonical is measured in
  3D, so it under-sizes unless the object's longest axis lies in the image plane;
* **front-surface depth** — it seats the centre at the median VISIBLE-surface depth,
  which is nearer than the true centre by the shape's front-to-centre offset under R.

The two are COUPLED (a size measured at the wrong depth is the wrong size), so they are
solved together: project the rotated canonical at the current estimate and match three
observed quantities — silhouette angular size, silhouette centre and median visible
depth.  No renderer, no gradients.
"""
from typing import Optional, Tuple

import numpy as np


def _project_p3d(P: np.ndarray, K: np.ndarray):
    """PyTorch3D camera points -> pixels.

    Inverts the observation's own back-projection (``depth_grounding._mask_center_scale``:
    ``X = -(u - cx)/fx * Z``, ``Y = -(v - cy)/fy * Z``), so the forward model here and
    the observation it is matched against cannot disagree about the convention.
    """
    fx, fy, cx, cy = K[0, 0], K[1, 1], K[0, 2], K[1, 2]
    z = np.maximum(P[:, 2], 1e-6)
    return cx - fx * P[:, 0] / z, cy - fy * P[:, 1] / z


def _silhouette_stats(P: np.ndarray, K: np.ndarray, bins: int = 64):
    """(angular size, bbox centre u, bbox centre v, median visible depth) of a posed
    point set.

    ``bins`` is a coarse z-buffer in PIXEL space: keep the nearest z per bin, then take
    the median over occupied bins.  This is what a depth sensor reports, and it must be
    computed over an area-uniform SURFACE sample -- mesh vertices cluster on rims and
    bias the statistic badly enough to flip its sign.
    """
    u, v = _project_p3d(P, K)
    z = P[:, 2]
    du, dv = np.ptp(u), np.ptp(v)
    a = max(du / K[0, 0], dv / K[1, 1])
    if not np.isfinite(a) or a <= 1e-8:
        return None
    iu = np.clip(((u - u.min()) / max(du, 1e-8) * (bins - 1)).astype(int), 0, bins - 1)
    iv = np.clip(((v - v.min()) / max(dv, 1e-8) * (bins - 1)).astype(int), 0, bins - 1)
    buf = np.full(bins * bins, np.inf)
    np.minimum.at(buf, iv * bins + iu, z)
    occ = buf[np.isfinite(buf)]
    d_vis = float(np.median(occ)) if occ.size else float(np.median(z))
    return a, 0.5 * (u.max() + u.min()), 0.5 * (v.max() + v.min()), d_vis


def refit_translation_scale(
    canonical_pts: np.ndarray,
    R: np.ndarray,
    seed_center: np.ndarray,
    seed_extent: float,
    K: np.ndarray,
    *,
    iters: int = 5,
    bins: int = 64,
) -> Optional[Tuple[float, np.ndarray]]:
    """Refit ``(scale, translation)`` for one frame, given the rotation.

    ``canonical_pts`` (N, 3) is the object's canonical shape in the SAME frame the pose
    maps from, unit-cube normalised; ``R`` (3, 3) the decoded row-vector object->camera
    rotation, so the posed points are ``s * (canonical_pts @ R) + t``.  ``seed_center``
    and ``seed_extent`` are the depth-grounded observation
    (:meth:`depth_grounding.DepthObservation.read`): the silhouette bbox centre
    back-projected at the median masked depth, and the metric silhouette span at that
    depth.

    Iterates the forward model rather than inverting a linearised one: a small-object
    closed form (``s = a·t_z/w_R``) over-inflates scale on objects that fill much of the
    frame, because the silhouette is generated by tangent rays at the object's NEAR side,
    not at its centre.  Each update line owns one residual (``s``<-size, ``t_z``<-depth,
    ``t_x,t_y``<-centre).

    Returns ``(scale, translation)`` or None when the geometry is degenerate.
    """
    W = np.asarray(canonical_pts, dtype=np.float64) @ np.asarray(R, dtype=np.float64)
    K = np.asarray(K, dtype=np.float64)
    fx, fy, cx, cy = K[0, 0], K[1, 1], K[0, 2], K[1, 2]
    d_med = float(seed_center[2])
    if d_med <= 1e-6 or seed_extent <= 0:
        return None
    a_obs = float(seed_extent) / d_med                       # observed angular size
    # The observed centre, back-projected; re-project it to pixels so the loop can match
    # centres without re-reading the mask.
    u_obs = cx - fx * float(seed_center[0]) / d_med
    v_obs = cy - fy * float(seed_center[1]) / d_med

    # Start from the observation itself (s = extent, t = centre).
    s = float(seed_extent)
    t = np.asarray(seed_center, dtype=np.float64).copy()
    for _ in range(iters):
        stats = _silhouette_stats(s * W + t, K, bins)
        if stats is None:
            return None
        a_pred, u_pred, v_pred, d_pred = stats
        s *= a_obs / a_pred                                  # match silhouette size
        t[2] += d_med - d_pred                               # match visible depth
        if t[2] <= 1e-6:
            return None
        t[0] += -(u_obs - u_pred) / fx * t[2]                # match silhouette centre
        t[1] += -(v_obs - v_pred) / fy * t[2]
    if not (np.isfinite(s) and np.isfinite(t).all()) or s <= 0:
        return None
    return s, t


def _grid_to_local(coords) -> np.ndarray:
    """Voxel indices ``[0, 63]`` -> points in local ``[-0.5, 0.5]``.

    ``(idx + 0.5) / 64 - 0.5``, the conversion ``interpolation.compute_object_tracks`` and
    the voxel-splat renderer in ``gaussian`` also use, so every cloud built from a 64^3 grid lands in
    the same box.  64 is the SLAT resolution and is fixed pipeline-wide
    (``shape_inversion`` hard-codes it identically).

    ``None`` for an empty or non-``(N, 3+)`` input, so a caller can treat "no usable grid
    here" and "no grid at all" the same way and fall through.
    """
    c = coords.detach().cpu().numpy() if hasattr(coords, "detach") else np.asarray(coords)
    c = np.asarray(c, dtype=np.float64)
    if c.ndim != 2 or c.shape[0] == 0:
        return None
    return (c[:, :3] + 0.5) / 64.0 - 0.5


def canonical_points_for_frame(state, obj_idx: int, frame_int: int) -> Optional[np.ndarray]:
    """The OCCUPANCY GRID to render for one object at one frame, in local ``[-0.5, 0.5]``.

    THIS FRAME's grid when the GT injection built one
    (``state.gt_perframe_voxel_correspondence[obj][frame]["coords"]``, populated by
    ``gt_shapes_inversion`` in ``mode=per_frame_meshes``), else the canonical grid.  A
    deforming object changes shape between timestamps, so rendering the canonical
    everywhere would match every frame against frame 0's geometry and drop the time
    dimension.

    Both branches are VOXEL GRIDS, deliberately.  The deformed mesh's VERTICES
    (``canonical_mesh_per_frame_verts``) are not a surface sampling: they cluster where
    curvature is and a flat face carries almost none, so splatting them at the sigma
    calibrated for a uniform grid renders a speckled wireframe.  The per-frame grid is
    voxelised on its own 64^3 lattice, so it is uniformly dense like the canonical one.

    ``frame_int`` is REQUIRED, so a caller cannot silently render frame 0's shape for
    every frame.  A caller that wants the canonical asks for the canonical timestamp.

    Returns None when the object has no grid at all, which is the signal to skip the refit
    rather than guess (a per-frame-only run has none at this point).
    """
    pf = (getattr(state, "gt_perframe_voxel_correspondence", None) or {}).get(obj_idx)
    entry = (pf or {}).get(int(frame_int))
    if entry is not None and entry.get("coords") is not None:
        pts = _grid_to_local(entry["coords"])
        if pts is not None:
            return pts
    for store in (state.gt_canonical_shape_coords, state.canonical_shape_coords):
        coords = (store or {}).get(obj_idx)
        if coords is None:
            continue
        pts = _grid_to_local(coords)
        if pts is not None:
            return pts
    return None


def _refit_one(inp, R: np.ndarray, t_cur: np.ndarray, s_cur: np.ndarray, mode: str,
               iters: int):
    """Run the refit for one frame and merge with the halves ``mode`` does not select.

    Returns ``(t_out (3,), s_out (3,), s_raw)`` or None; ``s_raw`` is this frame's own
    fitted scale before any ``mode`` merge, which is what a temporal reduce operates on.
    Shared by both call paths so the mode semantics cannot diverge between them.
    """
    fit = refit_translation_scale(inp["pts"], R, inp["center"], inp["extent"],
                                  inp["K"], iters=iters)
    if fit is None:
        return None
    s_new, t_new = fit
    t_out = t_new if mode in ("translation", "both") else t_cur
    s_out = (np.full(3, s_new, dtype=np.float64) if mode in ("scale", "both")
             else np.broadcast_to(s_cur, (3,)).copy())
    return t_out, s_out, float(s_new)


def _delta_angle_deg(R) -> float:
    """Rotation magnitude of a delta, in degrees -- 0 means ICP changed no orientation."""
    import torch

    return float(torch.rad2deg(torch.arccos(
        ((R.diagonal().sum() - 1) / 2).clamp(-1.0, 1.0))))


def compose_root_delta(dR_row, ds, dt, R_row_i, s_i, t_i):
    """Compose ``pose_i o dT`` -- one Sim(3) delta applied in the CANONICAL object frame.

    ROW-vector throughout (``posed = s * (x @ R) + t``), like ``pose_params``.

    **The row matrix of a stored pose is ``quaternion_to_matrix(q)``, UNTRANSPOSED** --
    it is exactly what ``refinement.apply_pose_to_gaussian`` right-multiplies by, and
    ``matrix_to_quaternion`` takes it straight back.  ``camera_pose_to_raw_tokens`` takes
    that same matrix.  ``dR_row`` is likewise ``axis_angle_to_matrix(aa)`` untransposed.

    Pass the untransposed matrices.  Transposing on the way in AND out is self-consistent
    but composes the delta in CAMERA space (``Q_new = Q @ dR`` instead of ``dR @ Q``): a
    different transform per frame as soon as two frames disagree in rotation, unable to
    express a shared canonical-frame correction, and it breaks the
    ``mv_shared_world_pose`` invariant.

    Applying the delta first and the pose second::

        s_i * ((ds * (x @ dR) + dt) @ R_i) + t_i
      = (s_i * ds) * (x @ (dR @ R_i)) + s_i * (dt @ R_i) + t_i

    so the composed pose is what this returns.  Because the delta rides on TOP of each
    frame's own pose, per-frame root MOTION survives -- the property that separates this
    from a shared-world pose, where the per-frame pose is instead fully DERIVED from one
    reference pose by a camera rebase
    (``pose_params.derive_perframe_pose_from_shared_decoded``).  The two are NOT
    interchangeable: substituting that one here would discard the object's motion.

    Returns ``(R_row_new, s_new, t_new)``.
    """
    return dR_row @ R_row_i, s_i * ds, s_i * (dt @ R_row_i) + t_i


#: Cap on the DUMPED prediction cloud.  It is one point per ``alpha > 0.5`` pixel, so a
#: large object at 512^2 is ~100k points and five views at two endpoints is ~25 MB for one
#: object.  Strided, not random, so two dumps of the same frame stay comparable.
ICP_DEBUG_MAX_POINTS = 50_000


def _gt_pixel_mask(data) -> np.ndarray:
    """The object's pixels intersected with the frame's validity, as a bool ``(H, W)``.

    The PIXEL selection behind the observed cloud, carried for the `icp_clouds/renders/`
    dump only.  NOT the whole story: `chamfer_gt_trim_factor` is a radius cut applied AFTER
    unprojection, so it is not a pixel mask and does not appear in the picture.
    """
    m = np.asarray(data["mask"]).astype(bool)
    v = data.get("valid_mask")
    return m if v is None else (m & np.asarray(v).astype(bool))


def _dump_icp_depths(d, stem, tag, obs, depth, alpha, keep) -> None:
    """The depth maps the two clouds were unprojected FROM, as `renders/*.png`.

    A cloud shows WHERE the points ended up; these show WHICH PIXELS produced them, which
    is what a mask or a filter question actually needs.  Both panels share one turbo scale
    taken from the observed depth, because two images each normalised to their own range
    cannot be compared by colour -- and comparing them is the entire point.

    ``keep`` is passed in from :func:`refinement.rendered_surface_keep`, the SAME mask the
    loss consumed, rather than recomputed here from ``alpha > 0.5``.

    Pixels outside each mask composite to white.  The observed panel is written once (the
    observation is loop-invariant); the rendered one is written per endpoint.
    """
    import os

    from .visualization import _compose_depth_alpha_image

    gt_d, gt_m = obs.get("gt_depth"), obs.get("gt_pixel_mask")
    rng = None
    if gt_d is not None and gt_m is not None and gt_m.any():
        rng = (float(gt_d[gt_m].min()), float(gt_d[gt_m].max()))
    os.makedirs(d, exist_ok=True)
    if gt_d is not None and gt_m is not None:
        _compose_depth_alpha_image(gt_d, gt_m.astype(float), vrange=rng).save(
            os.path.join(d, f"{stem}_gt_depth.png"))
    if depth is not None and keep is not None:
        _compose_depth_alpha_image(
            depth.detach(), keep.detach().float(), vrange=rng).save(
            os.path.join(d, f"{stem}_pred_depth_{tag}.png"))
        # Raw coverage beside the kept set: their difference IS what the filters removed.
        _compose_depth_alpha_image(
            depth.detach(), alpha.detach().clamp(0, 1), vrange=rng).save(
            os.path.join(d, f"{stem}_pred_depth_{tag}_unfiltered.png"))


def _dump_icp_clouds(out_dir, obj_idx: int, fk, tag: str, gt=None, pred=None,
                     obs=None, depth=None, alpha=None, keep=None) -> None:
    """Write the two clouds an ICP frame matches, for eyeballing in a 3D viewer.

    ``gt`` is the observed target and ``pred`` the rendered surface -- the SAME cloud the
    solver matches, obtained from the one ``rendered_surface_cloud`` definition rather
    than re-derived here.

    Written as ``icp_clouds/obj{N}_{frame_stem}_{gt,pred_TAG}.ply``, coloured apart (target
    green, prediction magenta) so both load into one viewer and separate by eye.  ``gt`` is
    passed only at the first call: it is loop-INVARIANT (``icp_frame_observation``: "the
    pose moves, the observation does not"), so writing it per endpoint would produce
    identical files inviting a diff for a difference that cannot exist.

    Non-fatal.  This is a debugging aid inside a solve that may have cost hours.
    """
    import os

    import trimesh

    from .frame_key import frame_key_stem

    try:
        d = os.path.join(str(out_dir), "icp_clouds")
        os.makedirs(d, exist_ok=True)
        stem = f"obj{obj_idx}_{frame_key_stem(fk)}"
        for name, pts, rgb in (("gt", gt, (60, 220, 60)), (f"pred_{tag}", pred, (220, 60, 220))):
            if pts is None or int(pts.shape[0]) == 0:
                continue
            v = pts.detach().cpu().numpy()
            if v.shape[0] > ICP_DEBUG_MAX_POINTS:
                v = v[:: (v.shape[0] + ICP_DEBUG_MAX_POINTS - 1) // ICP_DEBUG_MAX_POINTS]
            trimesh.PointCloud(
                vertices=v,
                colors=np.tile(np.array([*rgb, 255], dtype=np.uint8), (v.shape[0], 1)),
            ).export(os.path.join(d, f"{stem}_{name}.ply"))
        if obs is not None:
            # Additive: the PLY half stands alone, so a caller with no render still
            # gets its clouds.
            _dump_icp_depths(os.path.join(d, "renders"), stem, tag, obs,
                             depth, alpha, keep)
    except Exception as e:                       # noqa: BLE001 - debug output, never fatal
        print(f"    [warn] ICP cloud dump failed for obj {obj_idx} {fk}: {e}")


def _timestamp_delta_index(frames, per_frame_deltas: bool):
    """``(n_deltas, [delta_row for each frames[k]])`` — the per-frame optimisation axis.

    ``per_frame_deltas=False`` puts every entry on row 0 (the one shared Sim(3)).  With it
    on, entries are grouped by TIMESTAMP: a frame entry is a FrameKey ``(frame, view)``, so
    indexing by ENTRY would give each VIEW its own correction — a quantity one rigid object
    does not have, and (under ``mv_shared_world_pose``) a violation of the invariant that
    the views of a timestamp share a world placement.  Rows follow sorted timestamp order,
    so an index means the same thing across runs.

    Both the solve loop and the write-back index through this; computing the grouping
    twice is how the two would drift apart.  Monocular data is unaffected — every key
    there is view 0, so the grouping is the identity.
    """
    if not per_frame_deltas:
        return 1, [0] * len(frames)
    from .frame_key import as_frame_key

    keys = [as_frame_key(f["fk"]) for f in frames]
    row_of = {t: i for i, t in enumerate(sorted({fk.frame for fk in keys}))}
    return len(row_of), [row_of[fk.frame] for fk in keys]


def _build_frame_renderers(frames, sigma: float, device):
    """One ``PosedObjectRenderer`` per frame (``None`` where the frame has no source).

    A frame may carry a ready-made render SOURCE (``src_obj``) -- the block path renders
    the REAL reconstruction, whose geometry is exact -- or only a point cloud (``src``),
    which gets splatted into a Gaussian first.  Both go through
    ``make_posed_object_renderer``, which forwards ``_render_frame_with_pose``
    unchanged, so this is numerically identical to rendering it directly.

    Built ONCE: the shape is fixed while only the pose moves.  Memoised on identity
    because one canonical source shared by every frame must build ONE rasterisation
    context, not one per frame.  Both the key and the source are kept ALONGSIDE the
    renderer rather than just their ``id``, so an unreferenced object cannot be freed and
    its ``id`` reused by a later, different one -- returning the wrong renderer.
    Keyed on the PRE-splat source, because ``point_splat_gaussians`` returns a fresh
    object every call: keying on the splat's own id would miss every time and rebuild
    both the splat and its renderer per frame, which is the whole cost this memo exists
    to avoid -- and the splat path is the block default.
    """
    from genia.core.utils.gaussian import point_splat_gaussians
    from genia.core.utils.refinement import make_posed_object_renderer

    renderers, _built = [], {}
    for f in frames:
        key = f.get("src_obj") if f.get("src_obj") is not None else f.get("src")
        if key is None:
            renderers.append(None)
            continue
        if id(key) not in _built:
            source = (key if f.get("src_obj") is not None
                      else point_splat_gaussians(key, sigma, device))
            _built[id(key)] = (source, key, make_posed_object_renderer(source, device))
        renderers.append(_built[id(key)][2])
    return renderers


def _render_frame_pose(renderer, f, R_row, s, t, device, bg):
    """Render one frame at a composed pose -> ``(alpha, depth)``.

    The pose reaches the renderer as a wxyz quaternion of the ROW matrix, untransposed
    (see ``compose_root_delta``), and an isotropic scale expanded to three components.
    """
    import torch
    from pytorch3d.transforms import matrix_to_quaternion

    quat = matrix_to_quaternion(R_row.contiguous().unsqueeze(0)).squeeze(0)
    _, alpha, depth = renderer.render(
        quat, t, torch.as_tensor(s, device=device).reshape(1).expand(3),
        f["K"], f["W"], f["H"], device, bg_color=bg)
    return alpha, depth


# ---------------------------------------------------------------------------
# Closed-form point-to-plane ICP -- the primitives
# ---------------------------------------------------------------------------
#
# Point-to-plane correspondences + trimming + graduated non-convexity + a closed-form
# solve, keeping the one-directional GT->pred objective.  Row-vector convention
# throughout (see ``compose_root_delta``); the canonical box is centred on the origin, so
# no centroid anchor is needed.


def _delta_exp(v7):
    """A 7-vector increment ``(omega, nu, sigma)`` -> the Sim(3) delta ``(dR_row, ds, dt)``.

    ``sigma`` is a LINEAR scale step (``ds = 1 + sigma``), matching the Jacobian column
    built by ``_p2pl_rows_canonical``; the photometric solvers' ``log_ds``
    parameterisation is a different chart on the same group and the two never meet.

    ``axis_angle_to_matrix(omega)`` is used UNTRANSPOSED as a row matrix (``x @ R``),
    which rotates ``x`` by MINUS ``omega``.  That sign is why the row builder below emits
    ``n_c x x`` rather than ``x x n_c``.
    """
    from pytorch3d.transforms import axis_angle_to_matrix

    v = v7.reshape(-1)
    dR = axis_angle_to_matrix(v[:3].reshape(1, 3)).squeeze(0)
    return dR, (1.0 + v[6]).reshape(()), v[3:6].reshape(3)


def _p2pl_rows_canonical(p_r3, n_r3, g_r3, R_row, s, t):
    """Point-to-plane rows for one frame, expressed in the object's CANONICAL frame.

    ``(A (M,7), b (M,))`` for matched rendered points ``p_r3`` with normals ``n_r3``
    against observed points ``g_r3``, all in R3 camera space.

    THE POINT OF THE CANONICAL FRAME: a shared increment has to mean the same thing on
    every frame, and frames differ in pose.  A row built in camera space would describe a
    camera-space motion, so summing rows across frames would average unrelated
    quantities.  Pulling each row back through its own frame's pose makes one 7-vector
    describe one canonical-frame correction, which is exactly what ``compose_root_delta``
    then applies.

    The map a rendered point went through is ``p = F(s * (x @ R) + t)`` with
    ``F = diag(-1,-1,1)`` (``_transform_object_to_r3`` applies the P3D->R3 flip AFTER
    posing).  Undoing it gives the preimage ``x`` and the canonical normal ``n_c``.
    Perturbing ``x -> x + omega x x + nu + sigma x`` (the chart of ``_delta_exp``, whose
    row-convention rotation turns the omega term into ``-omega x x`` on ``x @ dR``) and
    projecting onto the plane normal gives

        n . dp = s * [ omega . (n_c x x) + n_c . nu + sigma * (x . n_c) ]

    hence the row ``s * [n_c x x, n_c, x . n_c]``.  The residual ``b = n . (p - g)`` is a
    dot product and so needs no frame change.

    Using the RENDERED point's preimage rather than the model's own points is what keeps
    self-occlusion in force: only surface a camera actually saw contributes a row.  It is
    exact to first order, the rendered surface moving rigidly with the object.
    """
    import torch

    F = torch.tensor([-1.0, -1.0, 1.0], dtype=p_r3.dtype, device=p_r3.device)
    x = ((p_r3 * F - t.reshape(1, 3)) / s) @ R_row.transpose(0, 1)
    n_c = (n_r3 * F) @ R_row.transpose(0, 1)
    A = torch.cat([torch.cross(n_c, x, dim=-1),
                   n_c,
                   (x * n_c).sum(-1, keepdim=True)], dim=-1) * s
    b = ((p_r3 - g_r3) * n_r3).sum(-1)
    return A, b


def _gnc_nu(it: int, max_iters: int, gnc_from: float, gnc_to: float) -> float:
    """The graduated-non-convexity kernel half-width at iteration ``it``, in units of the
    cloud's own resolution.

    Geometric interpolation from ``gnc_from`` to ``gnc_to`` over the WHOLE budget, so a
    run that converges early simply never reaches the narrow end -- which is harmless,
    the narrow end existing to reject outliers a converged fit no longer has.
    """
    if max_iters <= 1:
        return float(gnc_to)
    return float(gnc_from) * (float(gnc_to) / float(gnc_from)) ** (it / (max_iters - 1))


def _oriented_normals(P, neighborhood_size: int = 32):
    """Local-PCA normals for a camera-space R3 cloud, oriented toward the camera.

    The camera sits at the origin under this block's identity c2w, so "toward the camera"
    is simply ``n . p < 0`` and no normal-propagation graph is needed (these clouds are
    depth unprojections seen from one point).
    """
    import torch
    from pytorch3d.ops import estimate_pointcloud_normals

    if P.shape[0] < 3:
        return torch.zeros_like(P)
    k = int(min(neighborhood_size, max(2, P.shape[0] - 1)))
    # float32 for the same reason `_knn1` casts: this runs a KNN internally.
    N = estimate_pointcloud_normals(
        P.unsqueeze(0).to(torch.float32), neighborhood_size=k,
        disambiguate_directions=False).squeeze(0).to(P.dtype)
    flip = (N * P).sum(-1, keepdim=True) > 0
    return torch.where(flip, -N, N)


ICP_P2PL_NORMALS = ("pca", "depth")


def _depth_grid_normals(depth, K_t, keep):
    """Per-pixel normals for a RENDERED frame, from the depth grid rather than by PCA.

    The grid is structured, so a central difference is far better conditioned than a local
    PCA over the scattered cloud -- which matters most exactly where this solver works, on
    a voxel-splat render whose coverage is speckled.  Noisy normals are what the
    correspondence gate's ``cos`` test sheds.

    TWO reasons the 1px erode is load-bearing, not tidiness:

    1. ``depth_to_normals`` does not tolerate NaN -- a central difference spreads each NaN
       to its four neighbours and masking cannot clean it (``NaN * 0 = NaN``).
    2. gsplat returns ``RGB+ED``, an alpha-weighted EXPECTED depth, so a silhouette pixel
       blends foreground and background depth and its normal is meaningless.  ``alpha >
       0.5`` keeps such pixels; the erode is what removes them.

    The recipe is ``nan_to_num`` + erode, validity recovered as ``|n| > 0``.  An unreliable
    pixel comes back as the ZERO vector, which the normal gate rejects on its own.
    """
    import torch
    from genia.core.utils.refinement import _erode_bool_mask, depth_to_normals

    return depth_to_normals(torch.nan_to_num(depth), K_t,
                            mask=_erode_bool_mask(keep, 1))


def _face_camera(N, P):
    """Flip normals to point back at the camera, which sits at the origin under this
    block's identity c2w.  Idempotent on already-oriented normals, so it costs nothing to
    apply to both normal sources and guarantees one convention reaches the solve."""
    import torch

    return torch.where((N * P).sum(-1, keepdim=True) > 0, -N, N)


def _cloud_resolution(P) -> float:
    """Median nearest-neighbour spacing -- the length unit the GNC schedule is in.

    Expressing the kernel width in resolutions rather than metres is what lets ONE set of
    ``gnc_*`` defaults serve scenes at different scales and depths.
    """
    if P.shape[0] < 2:
        return 0.0
    d2 = _knn1(P, P, k=2)[0][:, 1]
    return float(d2.clamp_min(0).sqrt().median())


def _knn1(A, B, k: int = 1):
    """``(dists2, idx)`` of A's nearest neighbours in B, squeezed to ``(N,)``/``(N,k)``.

    Exists only to hold the float32 cast in ONE place: pytorch3d's KNN kernel is compiled
    for float32 and raises on float64, while the clouds reaching it are whatever the
    renderer produced.  The cast is for the SEARCH alone -- the indices come back and
    address the caller's own tensors at their own precision, so the least-squares solve
    still runs in float64.
    """
    import torch
    from pytorch3d.ops import knn_points

    out = knn_points(A.unsqueeze(0).to(torch.float32),
                     B.unsqueeze(0).to(torch.float32), K=k)
    d2 = out.dists.squeeze(0).to(A.dtype)
    idx = out.idx.squeeze(0)
    return (d2, idx) if k > 1 else (d2.squeeze(-1), idx.squeeze(-1))


def _match_gt_to_pred(G, NG, P, N, res: float, nu: float, trim: float,
                      normal_thr: float):
    """Correspondences G -> P, gated and weighted.  ``(idx_g, idx_p, w, d, kept)``.

    Three independent rejections, in order:

    1. DISTANCE -- ``d < 3 * nu * res``.  With the GNC schedule this is the solver's
       REACH: a seed further than that from the surface contributes no rows at all.
    2. NORMAL COMPATIBILITY -- ``cos(n_g, n_p) > normal_thr``.  Rejects a match that
       crosses to the far side of a thin structure.
    3. TRIM -- keep the lowest ``trim`` quantile of what survived, Chetverikov's rule.

    Survivors are then weighted by the WELSCH kernel on the correspondence distance,
    ``exp(-d^2 / (2 (nu res)^2))``, which is what makes the fit robust as the schedule
    narrows rather than relying on the gate alone.

    ``kept`` reports the three survival fractions so a cell that "did nothing" can be
    read off the history instead of guessed at.
    """
    import torch

    n_g = G.shape[0]
    empty = (torch.zeros(0, dtype=torch.long, device=G.device),) * 2
    zeros = torch.zeros(0, dtype=G.dtype, device=G.device)
    if n_g == 0 or P.shape[0] == 0 or res <= 0:
        return empty[0], empty[1], zeros, zeros, (0.0, 0.0, 0.0)

    d2, idx_p = _knn1(G, P)
    d = d2.clamp_min(0).sqrt()

    keep = d < (3.0 * nu * res)
    f_dist = float(keep.float().mean())
    if normal_thr > -1.0:
        cos = (NG * N[idx_p]).sum(-1)
        keep = keep & (cos > normal_thr)
    f_norm = float(keep.float().mean())
    if int(keep.sum()) > 10 and 0.0 < trim < 1.0:
        thr = torch.quantile(d[keep], float(trim))
        keep = keep & (d <= thr)
    f_trim = float(keep.float().mean())

    idx_g = keep.nonzero(as_tuple=True)[0]
    dk = d[idx_g]
    w = torch.exp(-(dk ** 2) / (2.0 * (nu * res) ** 2))
    return idx_g, idx_p[idx_g], w, dk, (f_dist, f_norm, f_trim)


def _solve_icp_increment(blocks, n_deltas: int, *, shared: bool, per_frame: bool,
                         fit_scale: bool, perframe_scale: bool, prior_weight: float,
                         e_acc, max_scale_step: float):
    """The hierarchical least-squares step.  ``(delta7 | None, eps (D,7) | None)``.

    THE POINT OF THE WHOLE SOLVER.  Unknowns are one SHARED 7-vector ``d`` and, under
    ``both``, one residual ``e_j`` per timestamp; every frame's rows read ``A_k (d + e_j)
    = -b_k``.  Because ``d`` appears in EVERY frame's rows and each ``e_j`` in only its
    own, the pooled evidence lands on ``d`` and only what one timestamp cannot explain
    with it lands on ``e_j`` -- the hierarchy as an estimator rather than as a schedule.
    A gradient step on per-leaf normalised gradients cannot express this: N per-frame
    triples would travel N times as far as the one shared triple and the split would
    invert.

    ``prior_weight`` (lambda) is the ridge on the ACCUMULATED residual ``e_acc + e_j``,
    i.e. a prior pulling each timestamp back to the shared solution, not merely damping
    this step.  Under ``both`` it must be > 0: the data alone is rank-deficient along
    ``(d + v, e_j - v)`` -- moving error between the shared and per-frame transforms
    leaves every residual unchanged -- and the prior is the ONLY thing that resolves it.
    That is the gauge freedom the docs call out under ``correction_granularity: both``,
    and here it is closed rather than left to the optimiser's path.

    Each frame's normal-equation block is normalised by its total weight, so lambda reads
    as "the prior versus ONE frame's evidence" independently of point counts.  (On
    multi-view data a timestamp holds V such blocks against one prior, so its residual is
    V times better evidenced -- correct, and worth knowing when reading lambda.)

    ``fit_scale=False`` drops the scale column everywhere (``icp_fit_scale: false``);
    ``perframe_scale=False`` drops it from the
    residuals only, which is ``correction_scale_control: shared`` -- the object has ONE
    size and the shared transform owns it.
    """
    import torch

    if not shared and not per_frame:
        raise ValueError("_solve_icp_increment: neither transform is free")
    if shared and per_frame and not (prior_weight > 0.0):
        raise ValueError(
            "correction_granularity='both' needs icp_perframe_prior_weight > 0 under the "
            "closed-form solver: with both transforms free the system is rank-deficient "
            "along (shared + v, per_frame - v) -- error moves between them at no cost -- "
            "and the prior is what decides the split.  Use 'shared' or 'per_frame' for an "
            "unregularised solve.")

    D = int(n_deltas)
    n_sh = 7 if shared else 0
    n_pf = 7 if per_frame else 0
    n_unk = n_sh + n_pf * D
    H = torch.zeros(n_unk, n_unk, dtype=torch.float64)
    g = torch.zeros(n_unk, dtype=torch.float64)

    for A, b, w, j in blocks:
        A = A.detach().to("cpu", torch.float64)
        b = b.detach().to("cpu", torch.float64)
        w = w.detach().to("cpu", torch.float64)
        wsum = float(w.sum())
        if wsum <= 0 or A.shape[0] == 0:
            continue
        Aw = A * (w / wsum).unsqueeze(-1)
        Hk = Aw.transpose(0, 1) @ A          # (7,7), already weight-normalised
        gk = Aw.transpose(0, 1) @ b          # (7,)
        sl = []
        if shared:
            sl.append(slice(0, 7))
        if per_frame:
            off = n_sh + 7 * int(j)
            sl.append(slice(off, off + 7))
        # d and e_j enter the residual as their SUM, so every cross block is the same Hk.
        for a in sl:
            g[a] += gk
            for c in sl:
                H[a, c] += Hk

    if per_frame and prior_weight > 0.0:
        # Prior on the ACCUMULATED residual: ||e_j + e_acc_j||^2, so a timestamp that has
        # already drifted is pulled back rather than merely slowed.
        for j in range(D):
            off = n_sh + 7 * j
            a = slice(off, off + 7)
            H[a, a] += float(prior_weight) * torch.eye(7, dtype=torch.float64)
            if e_acc is not None:
                g[a] += float(prior_weight) * e_acc[j].to(torch.float64)

    # Columns nothing may move: dropped by pinning them to zero with a unit row, which
    # keeps the indexing uniform (no reshaping of the system per mode).
    frozen = []
    if not fit_scale:
        if shared:
            frozen.append(6)
        if per_frame:
            frozen += [n_sh + 7 * j + 6 for j in range(D)]
    elif per_frame and not perframe_scale:
        frozen += [n_sh + 7 * j + 6 for j in range(D)]
    for i in frozen:
        H[i, :] = 0.0
        H[:, i] = 0.0
        H[i, i] = 1.0
        g[i] = 0.0

    ridge = 1e-9 * float(torch.diagonal(H).abs().sum()) / max(n_unk, 1)
    H = H + max(ridge, 1e-12) * torch.eye(n_unk, dtype=torch.float64)
    try:
        x = torch.linalg.solve(H, -g)
    except Exception:
        return None, None
    if not bool(torch.isfinite(x).all()):
        return None, None

    delta = x[:7] if shared else None
    eps = (x[n_sh:].reshape(D, 7) if per_frame else None)
    lim = float(max_scale_step)
    if delta is not None:
        delta = delta.clone()
        delta[6] = delta[6].clamp(-lim, lim)
    if eps is not None:
        eps = eps.clone()
        eps[:, 6] = eps[:, 6].clamp(-lim, lim)
    return delta, eps


def _icp_delta_closed_form(frames, sigma: float, steps: int, device, *,
                           per_frame_deltas: bool = False,
                           shared_correction: bool = False,
                           scale_control: str = "perframe",
                           trim: float = 0.8,
                           gnc_from: float = 8.0, gnc_to: float = 0.8,
                           normal_threshold: float = 0.5,
                           prior_weight: float = 1.0,
                           max_scale_step: float = 0.1,
                           fit_scale: bool = True,
                           normals: str = "pca",
                           keep_best: bool = False,
                           chamfer_reverse_weight: float = 0.0,
                           pred_trim_factor: float = 0.0,
                           debug_dir=None, debug_obj_idx: int = 0):
    """The ICP delta by POINT-TO-PLANE least squares.

    The shared/per-frame split is a hierarchical ESTIMATE (see ``_solve_icp_increment``):
    the shared transform sees every frame's rows, each per-timestamp residual only its own.

    Per iteration: render every frame at its current composite pose, unproject the
    rendered surface through ``rendered_surface_cloud``, take normals on both clouds,
    gate/trim/weight the GT->pred correspondences (``_match_gt_to_pred``), build
    canonical-frame rows (``_p2pl_rows_canonical``), and solve once for the shared
    increment and the per-timestamp residuals together.

    Runs entirely under ``no_grad``.  ``steps`` is a budget: the loop breaks early only
    once the increment stops moving, and the GNC schedule is spread over ``steps``.

    Returns ``(dR_all, ds_all, dt_all, history)``, one composite delta per timestamp
    (batched ``(D, ...)``).
    """
    import torch

    from genia.core.utils.timing import get_timer
    from genia.core.utils.pose_params import natives_to_freeze
    from genia.core.utils.refinement import (
        rendered_surface_cloud, rendered_surface_keep,
    )

    if shared_correction and not per_frame_deltas:
        # Unreachable from the dispatch, so it is a caller error rather than a mode.
        raise ValueError(
            "_icp_delta_closed_form: shared_correction=True requires "
            "per_frame_deltas=True (that pair is `correction_granularity: both`).  With "
            "per_frame_deltas=False the shared correction IS the only delta -- use "
            "shared_correction=False.")

    if normals not in ICP_P2PL_NORMALS:
        raise ValueError(f"icp_p2pl_normals must be one of {ICP_P2PL_NORMALS}, "
                         f"got {normals!r}")

    n_deltas, delta_of = _timestamp_delta_index(frames, per_frame_deltas)
    # Which transforms are free.  `shared` alone and `per_frame` alone are single-block
    # solves; `both` is the hierarchy, and only it needs the prior.
    solve_shared = (not per_frame_deltas) or shared_correction
    solve_perframe = per_frame_deltas
    # `correction_scale_control: shared` takes SIZE off the per-timestamp transform.
    perframe_scale = not (shared_correction
                          and natives_to_freeze("both", scale_control) == "scale")

    # Accumulated pose delta per timestamp, and the accumulated per-frame RESIDUAL the
    # prior pulls back toward zero.
    # Adopt the frames' own dtype rather than assuming float32: `compose_root_delta`
    # multiplies the accumulator by each frame's `R_row`, and torch refuses to mix.
    _dt_t = next((f["R_row"].dtype for f in frames if f.get("R_row") is not None),
                 torch.float32)
    dR_all = torch.eye(3, device=device, dtype=_dt_t).unsqueeze(0).repeat(n_deltas, 1, 1)
    ds_all = torch.ones(n_deltas, device=device, dtype=_dt_t)
    dt_all = torch.zeros(n_deltas, 3, device=device, dtype=_dt_t)
    e_acc = torch.zeros(n_deltas, 7, dtype=torch.float64)
    # `keep_best` snapshot.  The loop otherwise returns its LAST iterate, and the residual
    # is not monotone: the GNC schedule narrows the gate as it goes, so late iterations fit
    # a shrinking correspondence set and can drift back up.  The photometric solvers
    # restore their best; this is the same policy, opt-in.
    #
    # Note: it selects on the ONE-DIRECTIONAL chamfer, which is inflation-biased -- growing
    # the object lowers it.  Safe as a within-run tie-break, where the rise is gate-driven,
    # but `icp_p2pl_gnc_to` addresses the cause.
    best = None

    renderers = _build_frame_renderers(frames, sigma, device)
    bg = torch.zeros(3, device=device)
    history: list = []

    # Observed clouds never move, so their normals and resolution are computed once.
    gt_normals, gt_res = [], []
    for f in frames:
        tgt = f.get("tgt")
        if tgt is None or tgt.shape[0] == 0:
            gt_normals.append(None)
            gt_res.append(0.0)
            continue
        # `depth` uses the grid normals the observation carried; a frame built without
        # them falls back to PCA rather than failing -- the mode is a preference, not a
        # requirement.
        _gn = f.get("tgt_normals") if normals == "depth" else None
        gt_normals.append(_face_camera(_gn, tgt) if _gn is not None
                          else _oriented_normals(tgt))
        gt_res.append(_cloud_resolution(tgt))

    def _posed(k):
        j = delta_of[k]
        return compose_root_delta(dR_all[j], ds_all[j], dt_all[j],
                                  frames[k]["R_row"], frames[k]["s"], frames[k]["t"])

    def _dump(k, tag, depth, alpha, with_gt: bool):
        f = frames[k]
        with get_timer().exclude():
            _dump_icp_clouds(
                debug_dir, debug_obj_idx, f.get("fk", k), tag,
                gt=f["tgt"] if with_gt else None,
                obs=f, depth=depth, alpha=alpha,
                pred=rendered_surface_cloud(
                    depth, alpha, f["uu"], f["vv"], f["K"],
                    trim_factor=pred_trim_factor),
                keep=rendered_surface_keep(depth, alpha, f["K"]))

    with torch.no_grad():
        for it in range(int(steps)):
            nu = _gnc_nu(it, int(steps), gnc_from, gnc_to)
            blocks, per_frame_res, n_rows, gates = [], [], 0, []
            for k, (f, renderer) in enumerate(zip(frames, renderers)):
                if renderer is None or gt_normals[k] is None:
                    continue
                R_row, s_new, t_new = _posed(k)
                alpha, depth = _render_frame_pose(
                    renderer, f, R_row, s_new, t_new, device, bg)
                if normals == "depth":
                    # The dense grid map, indexed onto the cloud through the SAME
                    # selection that built it -- so a `pred_trim_factor` subset cannot
                    # slide the normals off the points.
                    P, _pidx, _keep = rendered_surface_cloud(
                        depth, alpha, f["uu"], f["vv"], f["K"],
                        trim_factor=pred_trim_factor, return_index=True)
                    N_pred = (None if P is None else
                              _depth_grid_normals(depth, f["K"], _keep)[_keep][_pidx])
                else:
                    P = rendered_surface_cloud(
                        depth, alpha, f["uu"], f["vv"], f["K"],
                        trim_factor=pred_trim_factor)
                    N_pred = None
                if P is None or P.shape[0] == 0:
                    continue          # empty render: UNDEFINED, never scored as 0
                if debug_dir is not None and it == 0:
                    _dump(k, "start", depth, alpha, with_gt=True)
                G, NG = f["tgt"], gt_normals[k]
                # The residual the history reports is the one-directional chamfer (mean
                # of SQUARED nearest distances), the same quantity the photometric
                # `chamfer_weight` term uses.
                res_k = float(_knn1(G, P)[0].mean())
                if chamfer_reverse_weight > 0.0:
                    res_k = res_k + float(chamfer_reverse_weight) * float(
                        _knn1(P, G)[0].mean())
                per_frame_res.append(res_k)

                N = _face_camera(N_pred, P) if N_pred is not None else _oriented_normals(P)
                ig, ip, w, _d, kept = _match_gt_to_pred(
                    G, NG, P, N, gt_res[k], nu, trim, normal_threshold)
                gates.append(kept)
                if ig.numel() == 0:
                    continue
                A, b = _p2pl_rows_canonical(
                    P[ip], N[ip], G[ig], R_row, s_new, t_new)
                blocks.append((A, b, w, delta_of[k]))
                n_rows += int(ig.numel())
                if chamfer_reverse_weight > 0.0:
                    # Symmetric objective: same row form, the roles of the two clouds
                    # swapped, down-weighted by `chamfer_reverse_weight`.
                    jp, jg, wr, _dr, _kr = _match_gt_to_pred(
                        P, N, G, NG, gt_res[k], nu, trim, normal_threshold)
                    if jp.numel() > 0:
                        Ar, br = _p2pl_rows_canonical(
                            P[jp], N[jp], G[jg], R_row, s_new, t_new)
                        blocks.append((Ar, br, wr * float(chamfer_reverse_weight),
                                       delta_of[k]))

            history.append({
                "iter": it,
                "residual": float(np.mean(per_frame_res)) if per_frame_res else float("nan"),
                "n_pairs": len(per_frame_res),
                "angle_deg": float(np.mean([_delta_angle_deg(m) for m in dR_all])),
                "scale": float(ds_all.mean()),
                "trans_norm": float(dt_all.norm(dim=-1).mean()),
                "per_frame": per_frame_res,
                # The first things to read when a run did nothing:
                # `nu` is where the schedule had reached, `gate_kept` the fraction of
                # observed points surviving each rejection, `perframe_residual_norm` how
                # much the per-timestamp transforms carry against the shared one.
                "nu": nu,
                "n_rows": n_rows,
                "gate_kept": [float(np.mean([g[i] for g in gates])) if gates else 0.0
                              for i in range(3)],
                "perframe_residual_norm": float(e_acc.norm(dim=-1).mean()),
            })
            # Snapshot BEFORE the step, so `best` is the delta that ACHIEVED this
            # residual rather than the one the step then moved it to.
            _r = history[-1]["residual"]
            if keep_best and _r == _r and (best is None or _r < best[0]):
                best = (_r, dR_all.clone(), ds_all.clone(), dt_all.clone())
            if not blocks:
                break

            delta, eps = _solve_icp_increment(
                blocks, n_deltas, shared=solve_shared, per_frame=solve_perframe,
                fit_scale=fit_scale, perframe_scale=perframe_scale,
                prior_weight=prior_weight, e_acc=e_acc, max_scale_step=max_scale_step)
            if delta is None and eps is None:
                break

            zero7 = torch.zeros(7, dtype=torch.float64)
            d_sh = (delta if delta is not None else zero7)
            moved = 0.0
            for j in range(n_deltas):
                e_j = (eps[j] if eps is not None else zero7)
                if eps is not None:
                    e_acc[j] = e_acc[j] + e_j
                v = (d_sh + e_j).to(device=device, dtype=dR_all.dtype)
                inc = _delta_exp(v)
                # Increment applied INNERMOST, matching the frame the rows were
                # linearised in; `compose_root_delta` is the Sim(3) group op, so feeding
                # it a delta where it expects a pose returns the product.
                nR, ns, nt = compose_root_delta(
                    inc[0], inc[1], inc[2], dR_all[j], ds_all[j], dt_all[j])
                dR_all[j], ds_all[j], dt_all[j] = nR, ns.reshape(()), nt
                moved = max(moved, float(v[:6].norm()), abs(float(v[6])))
            if moved < 1e-7:
                break

        if best is not None and best[0] < history[-1]["residual"]:
            # Restore BEFORE the end dump, so the pictures show the delta that is
            # returned rather than the one the loop happened to stop on.
            dR_all, ds_all, dt_all = best[1], best[2], best[3]
            # RECOMPUTE the delta stats -- do not inherit them from `history[-1]`.
            # `run_global_refine` prints `history[-1]`'s angle/scale/translation as "what
            # the block did", so copying the last iterate's numbers onto the restored best
            # would report a delta that was NOT applied.
            history.append({**history[-1], "iter": len(history),
                            "residual": best[0], "restored_best": True,
                            "angle_deg": float(np.mean([_delta_angle_deg(m)
                                                        for m in dR_all])),
                            "scale": float(ds_all.mean()),
                            "trans_norm": float(dt_all.norm(dim=-1).mean())})

        if debug_dir is not None:
            # AFTER the loop, not on the last iteration: the convergence break would
            # otherwise leave a run with no `end` dump at all.
            for k, (f, renderer) in enumerate(zip(frames, renderers)):
                if renderer is None:
                    continue
                R_row, s_new, t_new = _posed(k)
                alpha, depth = _render_frame_pose(
                    renderer, f, R_row, s_new, t_new, device, bg)
                _dump(k, "end", depth, alpha, with_gt=False)

    # Under `both` the shared part is already ABSORBED -- the caller sees one composite
    # delta per timestamp, not the gauge-free split.
    return dR_all.contiguous(), ds_all, dt_all, history


def _gaussian_for(gaussians, obj_idx, frame_idx):
    """Resolve one object/frame's Gaussian from either container shape.

    ``canonical_gaussians`` is ``{obj: gs}``; ``perframe_gaussians`` is
    ``{obj: {frame: gs}}``.  Both reach the refine blocks, so the disambiguation lives
    here once rather than at each call site (the same ``isinstance(..., dict)`` rule
    ``refine_poses_shared_world_for_sequence`` already uses).
    """
    if not gaussians:
        return None
    g = gaussians.get(obj_idx)
    return g.get(frame_idx) if isinstance(g, dict) else g


def icp_target_seed(base, obj_idx: int, fk) -> "Optional[int]":
    """The Chamfer target's subsample seed for one (object, frame, view), or None.

    ``base`` None means "draw fresh every run", so the sampling variance can be measured.
    Any int makes the draw reproducible while still differing per frame, so the views do
    not share one sample.

    ``_block_icp_frames`` reaches the target through this, so every refine block draws the
    same sample for the same (object, frame, view) and their numbers stay comparable.
    """
    from .frame_key import as_frame_key

    if base is None:
        return None
    fk = as_frame_key(fk)
    return int(base) + int(obj_idx) * 1_000_003 + int(fk.frame) * 1009 + int(fk.view)


def icp_frame_observation(sequence, obj_idx: int, fk, device, max_gt_points,
                          target_seed=0, trim_factor=3.0,
                          with_normals: bool = False):
    """One frame's OBSERVATION for an ICP term: ``{"tgt", "uu", "vv", "K", "H", "W"}``.

    The single definition of "what this object looks like in this frame" for the ICP
    refine block.

    Deliberately NOT ``core/pose_refit.py::_frame_refit_inputs``, the (t, s) refit's.
    That one returns None unless the frame carries ``raw_ss_modalities`` -- which the
    global path does not have (``run_global_refine`` passes
    ``perframe_raw_modalities=None`` unless ``mv_shared_world_pose``) -- and it computes
    silhouette stats that no ICP stage reads.  What this uses instead is the same
    ``_prepare_frame_data_for_refinement`` / ``_chamfer_gt_points_from_depth`` pair the
    blocks' own chamfer term already uses.

    Loop-INVARIANT: the pose moves, the observation does not.  Build it once.

    Returns None when the object is absent from the frame, the frame has no depth, or
    too few points survive -- the caller skips that frame rather than scoring it.
    """
    import torch

    from genia.core.utils.refinement import (
        _chamfer_gt_points_from_depth,
        _prepare_frame_data_for_refinement,
    )


    data = _prepare_frame_data_for_refinement(sequence, fk, obj_idx)
    if data is None or data.get("gt_depth") is None:
        return None
    # Seeded on (object, frame, view) so the target is REPRODUCIBLE across runs while
    # still differing between frames.  Unseeded, two runs of one ICP config would optimise
    # against different point draws.
    # `trim_factor` drops background points the mask bled onto BEFORE the subsample, so
    # the point cap is spent on the object.  A literal default rather than a config read:
    # this module imports typing + numpy only, by design, and every knob arrives as a
    # scalar; it must equal `CHAMFER_GT_TRIM_DEFAULT`.
    # ``with_normals`` additionally returns the per-point surface normal taken from the
    # depth GRID (`icp_p2pl_normals: depth`).  Off by default, so callers that do not
    # read it pay nothing for it.
    _gt = _chamfer_gt_points_from_depth(
        data["gt_depth"], data["K_matrix"], data["mask"], data.get("valid_mask"),
        max_gt_points, device, seed=icp_target_seed(target_seed, obj_idx, fk),
        trim_factor=trim_factor, with_normals=with_normals)
    tgt, tgt_normals = _gt if with_normals else (_gt, None)
    if tgt is None or tgt.shape[0] < 10:
        return None
    H, W = int(data["H"]), int(data["W"])
    vv, uu = torch.meshgrid(
        torch.arange(H, device=device, dtype=torch.float32),
        torch.arange(W, device=device, dtype=torch.float32), indexing="ij")
    return {"tgt": tgt.to(device).float(), "uu": uu, "vv": vv, "H": H, "W": W,
            "K": torch.as_tensor(data["K_matrix"], dtype=torch.float32, device=device),
            # Carried for the `icp_clouds/renders/` depth dump only -- nothing in the solve
            # reads them.  The PIXEL selection behind the target cloud; the 3D outlier trim
            # (`chamfer_gt_trim_factor`) is a radius cut applied AFTER unprojection, so it
            # is not a pixel mask and does not appear here.
            "gt_depth": np.asarray(data["gt_depth"]),
            "gt_pixel_mask": _gt_pixel_mask(data),
            # None unless `with_normals`; the closed-form solver reads it under
            # `icp_p2pl_normals: depth` and falls back to PCA when it is absent.
            "tgt_normals": (None if tgt_normals is None
                            else tgt_normals.to(device).float())}


def _block_icp_frames(state, sequence, obj_idx, device, gaussians, max_gt_points,
                      target_seed=0,
                      force_voxel_splat: bool = True,
                      trim_factor=3.0,
                      with_normals: bool = False):
    """Per-frame ICP inputs for a REFINE BLOCK: the observation, plus the DECODED pose
    and the RENDER SOURCE.

    The source is the frame's Gaussian; see :func:`_build_frame_renderers` for how it is
    rendered.

    A frame with none falls back to the canonical SHAPE, splatted one Gaussian per
    voxel (``src``).  This covers runs where no Stage-2 pass has run: Gaussians are
    decoded from SLATs, and a GT-injected or Stage-1 shape is occupancy, not a SLAT, so
    the geometry lives only in ``state.canonical_shape_coords``.
    ``force_voxel_splat`` takes that path even when a
    reconstruction IS available, which is how the two sources get compared on one run --
    but it PREFERS the splat rather than requiring it: with no grid for the object it
    falls back to the reconstruction, because the alternative is skipping the object and
    reporting a refined block that never ran.
    """
    import torch

    from genia.core.utils.quaternion_ops import quaternion_to_matrix

    from .frame_key import as_frame_key

    entries = state.tokens_by_object.get(obj_idx) or []
    # The splat cloud varies with the TIMESTAMP (this frame's GT voxel grid) but not with
    # the VIEW, so it is memoised per timestamp: the V views of one timestamp see one rigid
    # object in one shape and must share a tensor, or the solver -- which memoises its
    # renderer per distinct source object -- would build one splat and one rasterisation
    # context per view.  A run with no per-frame grids resolves the canonical for every
    # timestamp, so every entry is the same object and the memo collapses to one.
    pts_by_frame: dict = {}

    frames = []
    for fk, di in entries:
        if di.get("rotation") is None or di.get("translation") is None:
            continue
        def _recon_source():
            return _gaussian_for(gaussians, obj_idx, fk)

        src_obj = None if force_voxel_splat else _recon_source()
        src_pts = None
        if src_obj is None:
            _fi = int(as_frame_key(fk).frame)
            if _fi not in pts_by_frame:
                pts = canonical_points_for_frame(state, obj_idx, _fi)
                # Memoise the ABSENCE too, so a missing grid is not re-derived once
                # per entry.
                pts_by_frame[_fi] = None if pts is None else torch.as_tensor(
                    np.ascontiguousarray(pts), dtype=torch.float32, device=device)
            src_pts = pts_by_frame[_fi]
            if src_pts is None:
                # ``force_voxel_splat`` means PREFER the splat, not "skip the object when
                # there is no grid".  A shape-PREDICTING run populates no occupancy grid at
                # all (no GT injection, and Stage-1 leaves per-frame SLATs), so without
                # this fallback the block would silently refine nothing.  Falling back to
                # the reconstruction cannot change a run that HAS a grid.
                src_obj = _recon_source()
                if src_obj is None:
                    continue
        obs = icp_frame_observation(sequence, obj_idx, fk, device, max_gt_points,
                                    target_seed=target_seed, trim_factor=trim_factor,
                                    with_normals=with_normals)
        if obs is None:
            continue
        # `quaternion_to_matrix(q)` IS the row matrix -- it is what
        # `apply_pose_to_gaussian` right-multiplies by.  No transpose; see
        # `compose_root_delta`.
        R_row = quaternion_to_matrix(
            di["rotation"].reshape(1, 4))[0].detach().to(device).float().contiguous()
        frames.append({
            **obs, "fk": fk, "src_obj": src_obj, "src": src_pts, "R_row": R_row,
            "s": float(di["scale"].reshape(-1).detach().float().mean()),
            "t": di["translation"].reshape(3).detach().to(device).float(),
            "di": di,   # rides along so the write-back needs no second list kept in step
        })
    return frames


def apply_icp_refine(
    state, sequence, obj_idx: int, device, gaussians, *,
    per_frame_deltas: bool, shared_correction: bool = False,
    scale_control: str = "perframe",
    steps: int = 60, max_gt_points: int = 4000,
    force_voxel_splat: bool = True,
    fit_scale: bool = True,
    chamfer_reverse_weight: float = 0.0,
    chamfer_gt_trim_factor=3.0, pred_trim_factor: float = 0.0,
    p2pl_trim: float = 0.8, p2pl_gnc_from: float = 8.0, p2pl_gnc_to: float = 0.8,
    p2pl_normal_threshold: float = 0.5, perframe_prior_weight: float = 1.0,
    max_scale_step: float = 0.1, p2pl_normals: str = "pca",
    keep_best_iterate: bool = False,
    debug_dir=None, target_seed=0,
):
    """ICP pose refinement for one object inside a REFINE BLOCK, in place.

    Renders the canonical shape splatted one Gaussian per voxel by default
    (``force_voxel_splat``); with it off, the block's own reconstruction, falling back to
    the splat -- see :func:`_block_icp_frames`.  Correspondences run GT -> rendered, which
    is what makes it occlusion tolerant.

    ``per_frame_deltas`` selects the granularity: False gives ONE Sim(3) per object,
    composed onto every frame (so per-frame root MOTION survives); True gives one per
    timestamp.

    Writes DECODED pose fields, because that is what the refine blocks exchange -- the
    global path carries no raw modalities at all.  A frame that DOES carry
    them has them rewritten too, rotation included, so the two representations cannot
    disagree afterwards.

    The delta is solved by point-to-plane least squares (``icp_p2pl_*``,
    ``icp_perframe_prior_weight``); under ``correction_granularity: both`` the shared and
    per-timestamp transforms are estimated HIERARCHICALLY.  ``fit_scale=False`` holds the
    object's size.

    Returns ``(n_frames_rewritten, history)``; ``(0, [])`` when nothing was refinable.
    """
    import torch

    from genia.core.utils.gaussian import VOXEL_SPLAT_SIGMA_MULT
    from genia.core.utils.quaternion_ops import matrix_to_quaternion

    frames = _block_icp_frames(state, sequence, obj_idx, device, gaussians,
                               max_gt_points,
                               target_seed=target_seed,
                               force_voxel_splat=force_voxel_splat,
                               trim_factor=chamfer_gt_trim_factor,
                               # Only the `depth` normals mode reads them, and only it
                               # pays the extra `depth_to_normals` per frame.
                               with_normals=(p2pl_normals == "depth"))
    if not frames:
        return 0, []

    # sigma is read only by the voxel-splat fallback; a frame carrying a real render
    # source ignores it.  Voxel-edge units, so the two paths
    # calibrate identically.
    _sigma = VOXEL_SPLAT_SIGMA_MULT / 64.0
    dR_all, ds_all, dt_all, history = _icp_delta_closed_form(
        frames, _sigma, steps, device,
        per_frame_deltas=per_frame_deltas,
        shared_correction=shared_correction, scale_control=scale_control,
        trim=p2pl_trim, gnc_from=p2pl_gnc_from, gnc_to=p2pl_gnc_to,
        normal_threshold=p2pl_normal_threshold,
        prior_weight=perframe_prior_weight, max_scale_step=max_scale_step,
        fit_scale=fit_scale, normals=p2pl_normals, keep_best=keep_best_iterate,
        chamfer_reverse_weight=chamfer_reverse_weight,
        pred_trim_factor=pred_trim_factor,
        debug_dir=debug_dir, debug_obj_idx=obj_idx)

    n = 0
    # The same grouping the solve used, so the views of a timestamp write back the SAME
    # correction and the shared-world invariant survives it.
    _, delta_of = _timestamp_delta_index(frames, per_frame_deltas)
    for k, f in enumerate(frames):
        j = delta_of[k]
        R_new_row, s_new, t_new = compose_root_delta(
            dR_all[j], float(ds_all[j]), dt_all[j], f["R_row"], f["s"], f["t"])
        di = f["di"]
        # Batched storage shapes -- (1, 4) / (1, 3) / (1, 3), the same
        # `decode_perframe_poses_from_raw` writes.  Bare (4,) / (3,) break consumers
        # that do not reshape, e.g. PyTorch3D's `Translate`, which reads a 1-D tensor as
        # the X coordinate with Y and Z missing.
        di["rotation"] = matrix_to_quaternion(
            R_new_row.contiguous().unsqueeze(0)).detach()
        di["translation"] = t_new.detach().to(torch.float32).reshape(1, 3)
        di["scale"] = torch.full((1, 3), float(s_new), dtype=torch.float32,
                                 device=t_new.device)
        _sync_raw_modalities(di, R_new_row, t_new, s_new, device)
        n += 1
    return n, history


def _sync_raw_modalities(di, R_new_row, t_new, s_new, device) -> None:
    """Keep a frame's RAW tokens in step with the decoded pose just written.

    A no-op when the frame carries no raw modalities (the ordinary global-refine case) or
    no SSI context to invert through.  When it does carry them, leaving them stale is not
    harmless: ``decode_perframe_poses_from_raw`` would later overwrite the decoded pose
    from them and silently undo this refinement.

    Rotation IS rewritten, unlike ``apply_post_rotation_refit`` -- correcting it is the
    point here, and omitting it would discard the delta's rotation entirely.
    """
    import torch

    from genia.core.utils.pose_token_gt import camera_pose_to_raw_tokens

    raw = di.get("raw_ss_modalities")
    ps, psh = di.get("pointmap_scale"), di.get("pointmap_shift")
    if not raw or ps is None or psh is None:
        return
    tok = camera_pose_to_raw_tokens(
        R_new_row.contiguous(),          # it takes the same row matrix, untransposed
        t_new.to(torch.float32),
        torch.full((3,), float(s_new), dtype=torch.float32, device=device),
        torch.as_tensor(ps).to(device), torch.as_tensor(psh).to(device),
        downsample_factor=di.get("downsample_factor", 1),
    )
    raw["6drotation_normalized"] = tok["6drotation_normalized"].detach()
    raw["translation"] = tok["translation"].detach()
    raw["scale"] = tok["scale"].detach()
